from dotenv import load_dotenv
import os 
from langchain_openai import ChatOpenAI
from langchain_ollama import ChatOllama
# Chat model object is the primary interface for interacting with LLMs. It handles sending prompts to the model and receiving responses.
# System messages set the behavior of the AI model.
# The input are a list of messages that can include user messages, system messages, and assistant messages.
# AI messages are responses generated by the AI model.
from langchain_core.prompts import PromptTemplate
load_dotenv()
# A langchain chain is a sequence of actions or operations that process data using language models. The output of one step can be the input to the next step.




def main():
    print("Hello from langchain-course!")
    information= """Elon Reeve Musk (Pretoria, 28 de junio de 1971) es un empresario, inversor, activista político conservador,[3]​[4]​ y magnate.[nota 1]​ Es el fundador, consejero delegado e «ingeniero» en jefe de la empresa SpaceX; inversor ángel, director general y arquitecto de productos de Tesla, Inc.; fundador de The Boring Company; y cofundador de Neuralink y OpenAI.[nota 2]​ Además, es el director de tecnología de X Corp.[5]​ Entre enero y mayo de 2025, ejerció como administrador de facto del Departamento de Eficiencia Gubernamental de la Casa Blanca bajo la segunda presidencia de Donald Trump.[6]​[7]​

    Con un patrimonio neto estimado en poco más de 450 mil millones de dólares en octubre de 2025,[8]​ es la persona más rica del mundo según el índice de multimillonarios en tiempo real de Forbes.[9]​[10]​

    Musk nació y se crio en una rica familia de Pretoria (Sudáfrica). Su madre es canadiense y su padre un sudafricano blanco. Estudió brevemente en la Universidad de Pretoria antes de trasladarse a Canadá a los 17 años. Se matriculó en la Universidad de Queen y se trasladó a la Universidad de Pensilvania dos años después, donde se graduó en Economía y Física. En 1995 se trasladó a California para asistir a la Universidad Stanford, pero en su lugar decidió seguir una carrera empresarial, cofundando la empresa de software web Zip2 con su hermano Kimbal. Zip2 fue adquirida por Compaq por 307 millones de dólares en 1999. Ese mismo año, Musk cofundó el banco en línea X.com, que se fusionó con Confinity en 2000 para formar PayPal. La empresa fue comprada por eBay en 2002 por mil quinientos millones de dólares.

    En 2002, Musk fundó SpaceX, fabricante aeroespacial y empresa de servicios de transporte espacial, de la que es director general e ingeniero jefe. En 2003, se unió al fabricante de vehículos eléctricos Tesla Motors, Inc. (ahora Tesla, Inc.) como presidente y arquitecto de productos, convirtiéndose en su consejero delegado en 2008. En 2006, ayudó a crear SolarCity, ahora Tesla Energy, una empresa de servicios de energía solar que posteriormente fue adquirida por Tesla y se convirtió en Tesla Energy. En 2015, cofundó OpenAI, una empresa de investigación sin ánimo de lucro que promueve la inteligencia artificial amigable. En 2016, cofundó Neuralink, una empresa de neuro tecnología centrada en el desarrollo de interfaces cerebro-ordenador, y fundó The Boring Company, una empresa de construcción de túneles. También acordó la compra de la importante red social estadounidense Twitter en 2022 por 44 000 millones de dólares. Musk también ha propuesto el hyperloop. En noviembre de 2021, el director general de Tesla fue la primera persona de la historia en acumular una fortuna de trescientos mil millones de dólares.[11]​

    Ha sido criticado por hacer declaraciones poco científicas y controvertidas. En 2018, fue demandado por la Comisión de Bolsa y Valores de Estados Unidos (SEC) por tuitear falsamente que había conseguido financiación para una adquisición privada de Tesla. Llegó a un acuerdo con la SEC, pero no admitió su culpabilidad, renunciando temporalmente a su presidencia y aceptando limitaciones en el uso de su Twitter personal. En 2019, ganó un juicio por difamación presentado contra él por un espeleólogo británico que asesoró en el rescate de la cueva Tham Luang. Musk también ha sido criticado por difundir información errónea sobre la pandemia de COVID-19 y teorías de conspiración; y por sus controvertidas opiniones sobre asuntos como la inteligencia artificial, las criptomonedas y el transporte público.

    """
    summary_template = """Given the information {information}, about a person I want you to create:
    1. A short summary of no more than 50 words.
    2. Two interesting facts about the person."""

    summary_prompt_template = PromptTemplate(
        input_variables=["information"],template=summary_template
    ) # This is going to format input variable (information) into the template (summary_template).
    #llm=ChatOpenAI(temperature=0, model_name="gpt-5") 
    llm=ChatOllama(model="gemma3:270m", temperature=0)

    chain= summary_prompt_template | llm  #LCEL is the LangChain Expression Language that allows to create a chain using the components: prompt template and llm.
    # This pipe operator '|' connects the prompt template to the llm, creating a chain that first formats the prompt (prompt string) and then sends it to the language model for processing.
    # It is called Runnable Object in LangChain.

    response=chain.invoke(input={"information": information}) 
    print(response.content)
    # The chain.invoke is sending the input variable to the LLM
    # response is an AIMessage type


if __name__ == "__main__":
    main()

# Prompt is text input that LLM will process and wil return output.
# LLM is a class that represents a language model.